apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-demo-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: fastapi-secrets
    creationPolicy: Owner
  data:
    - secretKey: MY_ENV_VAR
      remoteRef:
        key: fastapi-demo
        property: MY_ENV_VAR
    - secretKey: ANOTHER_KEY
      remoteRef:
        key: fastapi-demo
        property: ANOTHER_KEY
